### ISSUE TITLE
Installation in Contao 4.9 nicht möglich

### ISSUE THREAD

**Issue by theDyingMountain** [hschottm/tags#56] opened 2020-02-25 09:06 UTC
In erhalte folgenden Fehler bei der Installation über den Contao Manager: 

`Error thrown while running command "cache:warmup --env=prod  
  ". Message: "Class 'tl_settings' not found" ["exception" => Error { …},"command" => "cache:warmup --env=prod","message" => "Class 'tl_settings' not found"]                                                                                                                                                   
  In tl_settings.php line 212:                                                                                                                       
  Attempted to load class "tl_settings" from the global namespace.           
  Did you forget a "use" statement? `

**Comment by fritzmg** [comment] 2020-02-25 09:11
Duplicate of https://github.com/hschottm/tags/pull/55

**Closed** 2020-02-25 09:16 UTC
